JSON_COMMANDS = {
    'DEVICEID': 'did',
    'SETBRIGHTNESS': 'setBrightness',
    'SETON': 'setOn',
    'SETOFF': 'setOff',
    'ACTIONS': 'actions',
    'ACTION': 'action',
    'TIMESTAMP': 'ts',
    'SETPOWERLEVEL': 'setPowerLevel',
    'SETCOLOR': 'setColor',
    'SETCOLORTEMPERATURE': 'setColorTemperature',
    'INCREASECOLORTEMPERATURE': 'increaseColorTemperature',
    'DECREASECOLORTEMPERATURE': 'decreaseColorTemperature',
    'VALUE': 'value',
    'POWERLEVELDELTA': 'powerLevelDelta',
    'BRIGHTNESS': 'brightness',
    'BRIGHTNESSDELTA': 'brightnessDelta',
    'COLOR': 'color',
    'COLOR_R': 'r',
    'COLOR_G': 'g',
    'COLOR_B': 'b',
    'COLORTEMPERATURE': 'colorTemperatureInKelvin',
    'POWERSTATE': 'powerState',
    'POWERLEVEL': 'powerLevel',
    'PARAMETERS': 'parameters',
    'NAME': 'name',


}
